# MATRIKS

Matriks adalah suatu susunan bilangan real atau bilangan kompleks (atau elemen-elemen) yang disusun dalam baris dan kolom sehingga membentuk jajaran persegi panjang.

### Cara memberi nama suatu matriks

Suatu matriks diberi nama dengan menggunakan huruf kapital seperti A, B, C, dan seterusnya, sedangkan anggotanya dinyatakan dengan huruf kecil. Anggota dari suatu matriks dapat pula dinyatakan dengan huruf kecil yang berindeks ganda (), dengan indeks pertama menyatakan di baris mana anggota itu terletak dan indeks kedua menyatakan di kolom mana anggota itu terletak. Sebagai contoh  artinya anggota tersebut terletak pada baris kesatu dan kolom kedua. Begitu juga  artinya anggota tersebut terletak pada baris kedua dan kolom keempat.

### Ordo/Ukuran/Order dari suatu matriks

Ordo/ukuran dari suatu matriks ditentukan oleh banyaknya baris dan kolom yang dimiliki oleh matriks tersebut. Contoh: Matriks A pada contoh di atas meniliki dua buah baris dan dua buah kolom, sehingga kita katakana matriks A berordo 2 x 2. Jika sebuah matriks memiliki i baris dan kolom, maka matriks tersebut berordo i x j, dapat dituliskan Ai.j

In [30]:
# import library numpy

import numpy as np

Gunakan np.array([matriks]) untuk membuat matriks dengan nilai yang dpat diisi sendiri

In [32]:
import numpy as np 
A = np.array([[1,3],[2,1]])
B = np.array([[3,0,4],[-1,-2,1]])
C = np.array([[-2,1],[4,1]])
D = np.array([[2],[6]])

print("A")
print(A,"\n")

print("B")
print(B,"\n")

print("C")
print(C,"\n")

print("D")
print(D,"\n")


A
[[1 3]
 [2 1]] 

B
[[ 3  0  4]
 [-1 -2  1]] 

C
[[-2  1]
 [ 4  1]] 

D
[[2]
 [6]] 



Gunakan np.random.randint(n,seze(=i,j) untuk membuat matriks dengan nilai int acak 0-n dan memeiliki baris i dan kolom j

In [35]:
E = np.random.randint(10,size=(2,2))
F = np.random.randint(10,size=(3,2))
G = np.random.randint(10,size=(3,3))
print("F")
print(E,"\n")

print("E")
print(F,"\n")

print("G")
print(G,"\n")

F
[[9 7]
 [6 7]] 

E
[[3 3]
 [1 7]
 [8 8]] 

G
[[4 8 1]
 [2 4 5]
 [6 2 9]] 



Untuk mengecek panjang baris dan kolom dapat menggunakan np.shape atau len

In [36]:
print("baris dan kolom matriks A\n",np.shape(A))
print("baris dan kolom matriks B\n", len(B),len(B[0]))

baris dan kolom matriks A
 (2, 2)
baris dan kolom matriks B
 2 3


## Operasi-operasi matriks

matriks yang ukurannya sama dapat dijumlahkan.Hasilnya adalah semua elemen yang bersesuaian ditambhkan dan ditulis dalam bentuk.


            (A+C) = a+c
        A+0=A dimana 0 matriks nol
            A+B=B+A
          (A+B)+C=A+(B+C)

# Operasi Matriks

## Penjumlahan 

Operasi matriks yang pertama kita bahas adalah penjumlahan matriks. Operasi matriks adalah penjumlahan 2 matriks yang letak komponennya sama. Sebenarnya, operasi matriks tidak jauh beda dengan operasi penjumlahan pada umumnya, tapi ada syarat matriks bisa dijumlahkan.

syarat matriks agar bisa dijumlahkan adalah dua matriks harus memiliki ordo yang sama. Contohnya seperti matriks di bawah ini. 


In [8]:
print("A")
print(A,"\n")

print("C")
print(C,"\n")

ac = A+C
print("hasil matriks A+C =")
print(ac,)

A
[[1 3]
 [2 1]] 

C
[[-2  1]
 [ 4  1]] 

hasil matriks A+C =
[[-1  4]
 [ 6  2]]


## Pengurangan 

Konsep pengurangan pada operasi matriks sama seperti cara pengerjaan penjumlahan, jadi tinggal mengurangkan masing-masing baris sesuai dengan urutannya. 
Syarat pengurangan matriks pun sama dengan penjumlahan, yaitu kedua matriks harus memiliki ordo yang sama sehingga bisa dioperasikan.

Dibawah ini merupakan contoh operasi pengurangan matriks : 

In [9]:
print("A")
print(A,"\n")

print("C")
print(C,"\n")

ac = A-C
print("hasil matriks A-C =")
print(ac,)

A
[[1 3]
 [2 1]] 

C
[[-2  1]
 [ 4  1]] 

hasil matriks A-C =
[[ 3  2]
 [-2  0]]


## Perkalian 

### Operasi Perkalian Matriks dengan Bilangan Real (Skalar)

Perkalian matriks dengan bilangan real (skalar) tidak memiliki persyaratan. Jadi, semua matriks dengan ordo apapun bisa dikalikan dengan bilangan real (skalar).

Dibawah ini merupakan contoh operasi perkalian matriks dengan bilangan saklar :



In [11]:
# perkalian dengan saklar 

# J adalah saklar dan A adalah matriks

J = 4
JA = J * A
print("matriks A")
print(A,"\n")
print("saklar J")
print(J,"\n")
print("hasil perkalian matriks A dengan saklar J")
print(JA,"\n")


matriks A
[[1 3]
 [2 1]] 

saklar J
4 

hasil perkalian matriks A dengan saklar J
[[ 4 12]
 [ 8  4]] 



### Perkalian Dua Matriks

1) Sifat tidak komutatif

AB tidak BA

2) Pada sifat distributif ini berkaitan dengan operasi penjumlahan matriks. Berikut contohnya:

X (Y + Z) = XY + XZ

(Y + Z) X = YX + ZX 


# Tugas perkalian Dua Matriks 

### Perkalian dua Matriks menggunakan perulangan 

In [26]:
listA = [[2,4],[2,5],[2,3]]

listB = [[3,5,1],[1,6,3]]
  
print("Matriks A",listA,"\n")
print("MAtriks B",listB,"\n")

print("panjang baris dan kolom")
print("Matriks A")
print(len(listA),len(listA[0]),"\n")
print("Matriks B")
print(len(listB),len(listB[0]),"\n")

# n adalah panjang baris matrix listA
n = len(listA)

# adalah panjang kolom matrix listA dan panjang baris matrix listB
m = len(listA[0])

# p adalah panjang baris matrix listB
p = len(listB[0])

hasil = []
# perulangan terjadi sebanyak panjang baris listA
for i in range(0,n):
  hasil1 = []
  # perulangan terjadi sebanyak panjang baris listB
  for j in range(0,p):
    jumlah = 0
    for k in range(0,m):
      jumlah += listA[i][k] * listB[k][j]
    hasil1.append(jumlah)
  hasil.append(hasil1)
print("hasil dari perkalian matrix :" "\n")
print(hasil,"\n")

Matriks A [[2, 4], [2, 5], [2, 3]] 

MAtriks B [[3, 5, 1], [1, 6, 3]] 

panjang baris dan kolom
Matriks A
3 2 

Matriks B
2 3 

hasil dari perkalian matrix :

[[10, 34, 14], [11, 40, 17], [9, 28, 11]] 



### Perkalian dua matriks dengan library numpy

In [27]:
MatriksA = np.array(([2,4],[2,5],[2,3]))
MatriksB = np.array(([2,5,1],[1,6,3]))

print(MatriksA,"\n")
print(MatriksB,"\n")

dot1 = np.dot(MatriksA,MatriksB)
dot2 = MatriksA.dot(MatriksB)

print(dot1,"\n")
print(dot2,"\n")

[[2 4]
 [2 5]
 [2 3]] 

[[2 5 1]
 [1 6 3]] 

[[ 8 34 14]
 [ 9 40 17]
 [ 7 28 11]] 

[[ 8 34 14]
 [ 9 40 17]
 [ 7 28 11]] 

